"use client";

import dynamic from "next/dynamic";
import {FormEvent,useEffect,useLayoutEffect,useMemo,useRef,useState} from "react";

import {useLocale} from "@/components/LocaleProvider";
import {API_URL} from "@/lib/api";
import {getSession} from "@/lib/session";
import type {WorkspaceTranslationKey} from "@/lib/i18n-core";
import type {Comment,Plan} from "@/lib/types";

function MapLoading(){const {t}=useLocale();return <div className="card map">{t("mapLoading")}</div>}
const MapView=dynamic(()=>import("./MapView"),{ssr:false,loading:()=> <MapLoading/>});
type BusyAction="copy"|"download"|"swipe"|"refine"|"versions"|"restore"|"comment"|"resolve"|"feedback"|"regenerate";
type Version={phien_ban:number;ly_do?:string;ngay_tao?:string};
type UiMessage={key:WorkspaceTranslationKey;values?:Record<string,string|number>};
type ChatItem={role:"assistant"|"user";text?:string;key?:WorkspaceTranslationKey};
const isRecord=(value:unknown):value is Record<string,unknown>=>typeof value==="object"&&value!==null;
const isCoordinate=(value:unknown)=>isRecord(value)&&typeof value.lat==="number"&&Number.isFinite(value.lat)&&value.lat>=-90&&value.lat<=90&&typeof value.lng==="number"&&Number.isFinite(value.lng)&&value.lng>=-180&&value.lng<=180;
const isSlot=(value:unknown)=>isRecord(value)&&typeof value.bat_dau==="string"&&typeof value.ket_thuc==="string"&&typeof value.dia_diem_id==="string"&&Boolean(value.dia_diem_id)&&typeof value.ten_dia_diem==="string"&&typeof value.mo_ta==="string"&&typeof value.chi_phi==="number"&&Number.isFinite(value.chi_phi)&&typeof value.ghi_chu==="string"&&isCoordinate(value.toa_do);
const isDay=(value:unknown)=>isRecord(value)&&typeof value.thu_tu==="number"&&Number.isInteger(value.thu_tu)&&typeof value.nhan_de==="string"&&Array.isArray(value.khoang_gio)&&value.khoang_gio.length<=100&&value.khoang_gio.every(isSlot);
const isPlan=(value:unknown):value is Plan=>isRecord(value)&&typeof value.tieu_de==="string"&&typeof value.tom_tat==="string"&&typeof value.chi_phi_moi_nguoi==="number"&&Number.isFinite(value.chi_phi_moi_nguoi)&&Array.isArray(value.ngay)&&value.ngay.length<=31&&value.ngay.every(isDay)&&isRecord(value.thoi_tiet)&&typeof value.thoi_tiet.tinh_trang==="string"&&typeof value.thoi_tiet.ghi_chu==="string";
const isComment=(value:unknown):value is Comment=>isRecord(value)&&typeof value.id==="string"&&typeof value.ten_hien_thi==="string"&&typeof value.noi_dung==="string"&&typeof value.da_giai_quyet==="boolean"&&typeof value.ngay_tao==="string";
const isVersion=(value:unknown):value is Version=>isRecord(value)&&typeof value.phien_ban==="number"&&Number.isInteger(value.phien_ban)&&value.phien_ban>0&&(value.ly_do===undefined||typeof value.ly_do==="string")&&(value.ngay_tao===undefined||typeof value.ngay_tao==="string");
const parseReplyKey=(value:unknown):WorkspaceTranslationKey|undefined=>value==="swipeSuccess"||value==="assistantWelcome"?value:undefined;
const isPastUtcDate=(value:unknown)=>{if(typeof value!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const parsed=new Date(`${value}T00:00:00Z`);return !Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===value&&value<new Date().toISOString().slice(0,10)};
async function safeJson(response:Response):Promise<unknown>{try{return await response.json()}catch{return null}}
function authHeader():Record<string,string>{try{const auth=localStorage.getItem("auth_token");return auth?{Authorization:`Bearer ${auth}`}:{}}catch{return {}}}
function preferredUnit():"metric"|"imperial"{try{const value=JSON.parse(localStorage.getItem("travel_preferences")||"null");return value?.don_vi==="imperial"?"imperial":"metric"}catch{return "metric"}}
async function copyShareLink(value:string):Promise<boolean>{
  try{
    if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);return true}
  }catch{}
  try{
    const textarea=document.createElement("textarea");
    textarea.value=value;
    textarea.setAttribute("readonly","true");
    textarea.style.position="fixed";
    textarea.style.opacity="0";
    document.body.appendChild(textarea);
    textarea.select();
    const copied=document.execCommand("copy");
    textarea.remove();
    return copied;
  }catch{return false}
}
const quickRefines={vi:[["Rẻ hơn","Re hon"],["Ít di chuyển","It di chuyen"],["Thêm cafe","Them cafe"]],en:[["Cheaper","Cheaper"],["Less travel","Less travel"],["More cafe","More cafe"]]} as const;

export default function PlanView({initial,token,version}:{initial:Plan;token:string;version:number}){
  const {locale,t}=useLocale();
  const [plan,setPlan]=useState(initial),[ver,setVer]=useState(version),[message,setMessage]=useState<UiMessage|null>(null);
  const [selectedId,setSelectedId]=useState(initial.ngay[0]?.khoang_gio[0]?.dia_diem_id),[activeDay,setActiveDay]=useState(0),[chat,setChat]=useState("");
  const [versions,setVersions]=useState<Version[]>([]),[showVersions,setShowVersions]=useState(false),[comments,setComments]=useState<Comment[]>([]),[showComments,setShowComments]=useState(false);
  const [commentName,setCommentName]=useState(t("companion")),[commentText,setCommentText]=useState(""),[showFeedback,setShowFeedback]=useState(false),[feedbackScore,setFeedbackScore]=useState(5),[feedbackText,setFeedbackText]=useState("");
  const [conversation,setConversation]=useState<ChatItem[]>([{role:"assistant",key:"assistantWelcome"}]),[busy,setBusy]=useState<BusyAction|null>(null);
  const [unit,setUnit]=useState<"metric"|"imperial">("metric");
  const busyRef=useRef<BusyAction|null>(null),mounted=useRef(true),previousCompanion=useRef(commentName),controllers=useRef(new Set<AbortController>()),currentToken=useRef(token);
  const slots=useMemo(()=>plan.ngay[activeDay]?.khoang_gio??[],[plan,activeDay]);
  const money=useMemo(()=>new Intl.NumberFormat(locale,{style:"currency",currency:"VND",maximumFractionDigits:0}),[locale]);
  const date=useMemo(()=>new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}),[locale]);
  const start=(action:BusyAction)=>{if(busyRef.current)return false;busyRef.current=action;setBusy(action);setMessage(null);return true};
  const active=()=>mounted.current&&currentToken.current===token;
  const finish=()=>{if(!active())return;busyRef.current=null;setBusy(null)};
  const fail=(key:"actionFailed"|"refineFailed"|"versionsFailed"|"commentsFailed"|"regenerateFailed")=>active()&&setMessage({key});
  const request=async(input:RequestInfo|URL,init:RequestInit={})=>{const requestToken=token,controller=new AbortController();controllers.current.add(controller);const timeout=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(input,{...init,signal:controller.signal});if(currentToken.current!==requestToken)throw new DOMException("Stale plan request","AbortError");return response}finally{clearTimeout(timeout);controllers.current.delete(controller)}};

  useEffect(()=>{const activeControllers=controllers.current;mounted.current=true;return()=>{mounted.current=false;activeControllers.forEach(controller=>controller.abort());activeControllers.clear()}},[]);
  useLayoutEffect(()=>{currentToken.current=token},[token]);
  useEffect(()=>()=>{controllers.current.forEach(controller=>controller.abort());controllers.current.clear()},[token]);
  useEffect(()=>{busyRef.current=null;setBusy(null);setPlan(initial);setVer(version);setSelectedId(initial.ngay[0]?.khoang_gio[0]?.dia_diem_id);setActiveDay(0);setVersions([]);setShowVersions(false);setComments([]);setShowComments(false);setShowFeedback(false);setMessage(null);setConversation([{role:"assistant",key:"assistantWelcome"}])},[token,initial,version]);
  useEffect(()=>{const next=t("companion");setCommentName(current=>current===previousCompanion.current?next:current);previousCompanion.current=next},[locale,t]);
  useEffect(()=>{const sync=()=>setUnit(preferredUnit());sync();window.addEventListener("travel-preferences-changed",sync);return()=>window.removeEventListener("travel-preferences-changed",sync)},[]);
  useEffect(()=>{setActiveDay(day=>Math.min(day,Math.max(0,plan.ngay.length-1)))},[plan.ngay.length]);
  useEffect(()=>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),30000);let active=true;(async()=>{try{const response=await fetch(`${API_URL}/api/plans/${token}/comments`,{signal:controller.signal,headers:{"X-Session-Id":getSession()}});const data=await safeJson(response);if(!response.ok||!isRecord(data)||!Array.isArray(data.ds_binh_luan)||!data.ds_binh_luan.every(isComment))throw new Error();if(active&&mounted.current)setComments(data.ds_binh_luan)}catch(error){if(active&&mounted.current)setMessage({key:"commentsFailed"})}})();return()=>{active=false;clearTimeout(timeout);controller.abort()}},[token]);
  useEffect(()=>{try{localStorage.setItem(`offline-plan:${token}`,JSON.stringify({plan,version:ver,savedAt:new Date().toISOString()}))}catch{setMessage({key:"offlineSaveFailed"})}},[plan,token,ver]);

  async function copy(){if(!start("copy"))return;try{setMessage({key:await copyShareLink(location.href)?"copied":"copyFailed"})}finally{finish()}}
  function downloadJson(){if(!start("download"))return;let url:string|null=null,anchor:HTMLAnchorElement|null=null;try{const blob=new Blob([JSON.stringify(plan,null,2)],{type:"application/json"});url=URL.createObjectURL(blob);anchor=document.createElement("a");anchor.href=url;anchor.download=`itinerary-${token}.json`;anchor.style.display="none";document.body.appendChild(anchor);anchor.click()}catch{fail("actionFailed")}finally{anchor?.remove();if(url)URL.revokeObjectURL(url);finish()}}
  async function swipe(id:string){if(!start("swipe"))return;const session=getSession();try{const response=await request(`${API_URL}/api/plans/${token}/swipe`,{method:"PATCH",headers:{"Content-Type":"application/json","X-Session-Id":session,...authHeader()},body:JSON.stringify({diem_bi_loai:id,phien_ban:ver,ma_phien:session})}),data=await safeJson(response);if(!response.ok||!isRecord(data)||!isPlan(data.ke_hoach_moi)||typeof data.phien_ban!=="number"||!Number.isInteger(data.phien_ban)||data.phien_ban<=0)throw new Error();if(!active())return null;const oldIds=new Set(plan.ngay.flatMap(day=>day.khoang_gio).map(slot=>slot.dia_diem_id));const replacement=data.ke_hoach_moi.ngay.flatMap(day=>day.khoang_gio).find(slot=>!oldIds.has(slot.dia_diem_id));setPlan(data.ke_hoach_moi);setVer(data.phien_ban);setSelectedId(replacement?.dia_diem_id??data.ke_hoach_moi.ngay[0]?.khoang_gio[0]?.dia_diem_id);setMessage({key:"swipeSuccess"});return replacement?.ten_dia_diem??null}catch{fail("actionFailed");return null}finally{finish()}}
  async function applyRefine(text:string){const messageText=text.trim();if(!messageText||!start("refine"))return;setConversation(items=>[...items,{role:"user",text:messageText}]);setChat("");const session=getSession();try{const response=await request(`${API_URL}/api/plans/${token}/refine`,{method:"POST",headers:{"Content-Type":"application/json","X-Session-Id":session,...authHeader()},body:JSON.stringify({message:messageText,phien_ban:ver,ma_phien:session,dia_diem_dang_chon:selectedId})}),data=await safeJson(response),replyKey=isRecord(data)?parseReplyKey(data.tra_loi_key):undefined;if(!response.ok||!isRecord(data)||!isPlan(data.ke_hoach)||typeof data.phien_ban!=="number"||!Number.isInteger(data.phien_ban)||data.phien_ban<=0||!replyKey)throw new Error();if(!active())return;setPlan(data.ke_hoach);setVer(data.phien_ban);setSelectedId(data.ke_hoach.ngay[0]?.khoang_gio[0]?.dia_diem_id);setConversation(items=>[...items,{role:"assistant",key:replyKey}])}catch{if(active())setConversation(items=>[...items,{role:"assistant",key:"refineFailed"}])}finally{finish()}}
  async function sendChat(event:FormEvent){event.preventDefault();await applyRefine(chat)}
  async function loadVersions(){if(showVersions){setShowVersions(false);return}if(!start("versions"))return;try{const session=getSession(),response=await request(`${API_URL}/api/plans/${token}/versions`,{headers:{"X-Session-Id":session,...authHeader()}}),data=await safeJson(response);if(!response.ok||!isRecord(data)||!Array.isArray(data.ds_phien_ban)||!data.ds_phien_ban.every(isVersion)||new Set(data.ds_phien_ban.map(item=>item.phien_ban)).size!==data.ds_phien_ban.length)throw new Error();if(!active())return;setVersions(data.ds_phien_ban);setShowVersions(true)}catch{fail("versionsFailed")}finally{finish()}}
  async function restore(target:number){if(!start("restore"))return;const session=getSession();try{const response=await request(`${API_URL}/api/plans/${token}/versions/${target}/restore`,{method:"POST",headers:{"Content-Type":"application/json","X-Session-Id":session,...authHeader()},body:JSON.stringify({phien_ban_hien_tai:ver,ma_phien:session})}),data=await safeJson(response);if(!response.ok||!isRecord(data)||!isPlan(data.ke_hoach)||typeof data.phien_ban!=="number"||!Number.isInteger(data.phien_ban)||data.phien_ban<=0)throw new Error();if(!active())return;setPlan(data.ke_hoach);setVer(data.phien_ban);setSelectedId(data.ke_hoach.ngay[0]?.khoang_gio[0]?.dia_diem_id);setShowVersions(false);setMessage({key:"restoreSuccess",values:{target,version:data.phien_ban}})}catch{fail("actionFailed")}finally{finish()}}
  async function addComment(event:FormEvent){event.preventDefault();if(!commentText.trim()||!commentName.trim()||!start("comment"))return;const session=getSession();try{const response=await request(`${API_URL}/api/plans/${token}/comments`,{method:"POST",headers:{"Content-Type":"application/json",...authHeader()},body:JSON.stringify({noi_dung:commentText.trim(),ten_hien_thi:commentName.trim(),ma_phien:session})}),data=await safeJson(response);if(response.status===401){try{localStorage.removeItem("auth_token")}catch{}}if(!response.ok||!isRecord(data)||!isComment(data.binh_luan))throw new Error();if(!active())return;const savedComment=data.binh_luan;setComments(items=>[...items,savedComment]);setCommentText("");setMessage({key:"commentAdded"})}catch{fail("commentsFailed")}finally{finish()}}
  async function resolveComment(comment:Comment){if(!start("resolve"))return;const session=getSession();try{const response=await request(`${API_URL}/api/plans/${token}/comments/${encodeURIComponent(comment.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json",...authHeader()},body:JSON.stringify({da_giai_quyet:!comment.da_giai_quyet,ma_phien:session})}),data=await safeJson(response);if(response.status===401){try{localStorage.removeItem("auth_token")}catch{}}if(!response.ok||!isRecord(data)||!isComment(data.binh_luan))throw new Error();if(!active())return;const updatedComment=data.binh_luan;setComments(items=>items.map(item=>item.id===comment.id?updatedComment:item))}catch{fail("commentsFailed")}finally{finish()}}
  async function submitFeedback(event:FormEvent){event.preventDefault();if(!start("feedback"))return;const session=getSession();try{const response=await request(`${API_URL}/api/plans/${token}/feedback`,{method:"POST",headers:{"Content-Type":"application/json",...authHeader()},body:JSON.stringify({diem:feedbackScore,noi_dung:feedbackText.trim(),ma_phien:session})});if(response.status===401){try{localStorage.removeItem("auth_token")}catch{}}if(!response.ok)throw new Error();if(!active())return;setShowFeedback(false);setMessage({key:"feedbackThanks"})}catch{fail("actionFailed")}finally{finish()}}
  async function regenerate(){if(!start("regenerate"))return;const session=getSession(),nonceKey=`regenerate-nonce:${token}`;let nonce="";try{nonce=sessionStorage.getItem(nonceKey)||crypto.randomUUID();sessionStorage.setItem(nonceKey,nonce)}catch{nonce=crypto.randomUUID()}try{const response=await request(`${API_URL}/api/plans/${token}/regenerate`,{method:"POST",headers:{"Content-Type":"application/json","X-Session-Id":session,...authHeader()},body:JSON.stringify({ma_phien:session,nonce})}),data=await safeJson(response);if(!response.ok||!isRecord(data)||typeof data.token!=="string"||!/^[A-Za-z0-9_-]+$/.test(data.token))throw new Error();if(!active())return;try{sessionStorage.removeItem(nonceKey)}catch{}location.assign(`/plan/${data.token}`)}catch{fail("regenerateFailed");finish()}}
  const canFeedback=isPastUtcDate(plan.ngay_di),disabled=busy!==null,quickActions=locale==="vi"?quickRefines.vi:quickRefines.en;
  const selectSlot=(id:string)=>setSelectedId(id);

  return <main className="workspace-page">
    <header className="trip-header"><div><div className="eyebrow">{t("workspaceEyebrow")}</div><h1>{plan.tieu_de}</h1><p>{plan.tom_tat}</p></div><div className="trip-actions"><button className="secondary" onClick={copy} disabled={disabled}>{t("share")}</button><a className="secondary button-link" href={`${API_URL}/api/plans/${token}/itinerary.pdf`}>{t("downloadPdf")}</a><a className="secondary button-link" href={`${API_URL}/api/plans/${token}/calendar.ics`}>{t("addCalendar")}</a><button className="secondary" onClick={downloadJson} disabled={disabled}>{t("downloadJson")}</button><button className="secondary" onClick={()=>setShowComments(value=>!value)}>{t("comments")} {comments.length}</button>{canFeedback&&<button className="secondary" onClick={()=>setShowFeedback(value=>!value)}>{t("feedback")}</button>}<button className="secondary" onClick={loadVersions} disabled={disabled}>{t("versions",{version:ver})}</button><button className="secondary" onClick={regenerate} disabled={disabled}>{t("regenerate")}</button></div></header>
    <div className="trip-facts" aria-label={t("tripSummary")}><span>☁ {plan.thoi_tiet.tinh_trang}{plan.thoi_tiet.nhiet_do_max!==undefined?` · ${unit==="imperial"?Math.round(plan.thoi_tiet.nhiet_do_max*9/5+32):plan.thoi_tiet.nhiet_do_max}°${unit==="imperial"?"F":"C"}`:""}</span><span>{money.format(plan.chi_phi_moi_nguoi)} / {t("perPerson")}</span><span>{t("places",{count:slots.length})}</span></div>
    {message&&<div className="status" role="status">{t(message.key,message.values)}</div>}{busy&&<div className="status" role="status">{t("busy")}</div>}
    {showVersions&&<section className="version-drawer card"><div className="panel-title">{t("versionHistory")}</div>{versions.map(entry=>{const parsedDate=entry.ngay_tao?new Date(entry.ngay_tao):null;const dateLabel=parsedDate&&!Number.isNaN(parsedDate.getTime())?` · ${date.format(parsedDate)}`:"";return <div className="version-row" key={entry.phien_ban}><div><strong>{t("version",{version:entry.phien_ban})}</strong><small>{entry.ly_do||t("scheduleUpdate")}{dateLabel}</small></div>{entry.phien_ban!==ver&&<button className="secondary" disabled={disabled} onClick={()=>restore(entry.phien_ban)}>{t("restore")}</button>}</div>})}</section>}
    {showComments&&<section className="comment-drawer card"><div className="panel-title">{t("groupDiscussion")}</div><div className="comment-list">{comments.length===0&&<p className="disclaimer">{t("noComments")}</p>}{comments.map(comment=><article className={comment.da_giai_quyet?"comment resolved":"comment"} key={comment.id}><div><strong>{comment.ten_hien_thi}</strong><p>{comment.noi_dung}</p></div><button className="secondary" disabled={disabled} onClick={()=>resolveComment(comment)}>{comment.da_giai_quyet?t("reopen"):t("resolved")}</button></article>)}</div><form className="comment-form" onSubmit={addComment}><input value={commentName} onChange={event=>setCommentName(event.target.value)} maxLength={80} aria-label={t("displayName")} required/><input value={commentText} onChange={event=>setCommentText(event.target.value)} maxLength={1000} placeholder={t("commentPlaceholder")} aria-label={t("commentPlaceholder")} required/><button className="primary" disabled={disabled}>{t("sendComment")}</button></form></section>}
    {showFeedback&&<form className="feedback-card card" onSubmit={submitFeedback}><div className="panel-title">{t("tripReview")}</div><label>{t("rating")}<select value={feedbackScore} disabled={disabled} onChange={event=>setFeedbackScore(Number(event.target.value))}>{[5,4,3,2,1].map(score=><option value={score} key={score}>{score}/5</option>)}</select></label><textarea value={feedbackText} disabled={disabled} onChange={event=>setFeedbackText(event.target.value)} maxLength={2000} placeholder={t("feedbackPlaceholder")} aria-label={t("feedbackPlaceholder")}/><button className="primary" disabled={disabled}>{t("sendFeedback")}</button></form>}
    <div className="workspace"><aside className="chat-panel card" aria-label={t("tripAssistant")}><div className="panel-title"><span className="assistant-dot"/>{t("tripAssistant")}</div><div className="messages" aria-live="polite">{conversation.map((item,index)=><div key={index} className={`bubble ${item.role}`}>{item.key?t(item.key):item.text}</div>)}</div><div className="quick-actions">{quickActions.map(([label,prompt])=><button type="button" className="chip" disabled={disabled} onClick={()=>{void applyRefine(prompt)}} key={prompt}>{label}</button>)}</div><form className="chat-box" onSubmit={sendChat}><input value={chat} disabled={disabled} onChange={event=>setChat(event.target.value)} placeholder={t("chatPlaceholder")} aria-label={t("chatPlaceholder")}/><button disabled={disabled} aria-label={t("send")}>↑</button></form></aside>
      <section className="itinerary-panel card"><div className="panel-title">{t("itinerary")}</div><div className="day-tabs">{plan.ngay.map((day,index)=><button className={index===activeDay?"active":""} onClick={()=>setActiveDay(index)} key={`${day.thu_tu}-${index}`}>{day.nhan_de}</button>)}</div><div className="timeline">{slots.map((slot,index)=><article className={`slot ${selectedId===slot.dia_diem_id?"selected":""}`} key={`${activeDay}-${index}-${slot.dia_diem_id}`}><button type="button" className="slot-select" aria-pressed={selectedId===slot.dia_diem_id} aria-label={slot.ten_dia_diem} onClick={()=>selectSlot(slot.dia_diem_id)}/><div className="stop-index">{index+1}</div><strong>{slot.bat_dau}<br/><span>{slot.ket_thuc}</span></strong><div><h3>{slot.ten_dia_diem}</h3><p>{slot.mo_ta}</p><small>{money.format(slot.chi_phi)} · {slot.ghi_chu}</small>{slot.nguon_url&&<a className="source" href={slot.nguon_url} target="_blank" rel="noreferrer">{t("source",{source:slot.nguon||slot.nguon_url})}</a>}</div><button className="icon-action" disabled={disabled} onClick={()=>{void swipe(slot.dia_diem_id)}} aria-label={t("swapPlace",{place:slot.ten_dia_diem})}>↻</button></article>)}</div></section>
      <section className="map-panel"><MapView slots={slots} selectedId={selectedId} onSelect={setSelectedId}/><div className="map-legend card">{t("mapLegend")}</div></section></div>
    <p className="disclaimer">{t("estimateDisclaimer",{weather:plan.thoi_tiet.ghi_chu})}</p>
  </main>
}
